In [2]:
import numpy as np 

In [3]:
a = np.array([
    [1,2],
    [3,4]
])
b = np.array([
    [5,6],
    [7,8]
])

In [4]:
c1 = a * b # element wise 
c2 = a @ b # matrix multiplication

In [5]:
c1

array([[ 5, 12],
       [21, 32]])

In [6]:
c2

array([[19, 22],
       [43, 50]])

In [8]:
c3 = np.dot(a, b)
c3
# matrix multiplication

array([[19, 22],
       [43, 50]])

In [10]:
c4 = np.multiply(a, b)
c4
# element wise 

array([[ 5, 12],
       [21, 32]])

In [12]:
c5 = np.inner(a, b)
c5
# sum: a-1st row *  b-1st row      sum: a-1st row * b-1st row
# sum: a-2nd row * b-1st row       sum: a-2nd row * b-2nd row

array([[17, 23],
       [39, 53]])

In [13]:
c6 = np.outer(a, b)
c6

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])